"""create_client_program_model

Revision ID: 4375a48af9ff
Revises: cc6b0fe62f73
Create Date: 2025-04-26 19:38:48.168792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4375a48af9ff'
down_revision = 'cc6b0fe62f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('program_id', sa.INTEGER(), nullable=False),
    sa.Column('enrollment_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['health_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'program_id', name='unique_client_program')
    )
    # ### end Alembic commands ###
