"""added subject column

Revision ID: bebcae8ccd80
Revises: 4375a48af9ff
Create Date: 2025-04-26 21:55:12.850683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebcae8ccd80'
down_revision = '4375a48af9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_programs', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
